// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: "AIzaSyDAheGqF8-qH5LNLpW2jk83hsqX_D4-0cI",
//     authDomain: "Queen's Place-c73f2.firebaseapp.com",
//     projectId: "Queen's Place-c73f2",
//     storageBucket: "Queen's Place-c73f2.appspot.com",
//     messagingSenderId: "920769746084",
//     appId: "1:920769746084:web:31738e1bc9eacb70f04231",
//     measurementId: "G-Y6HC417FL4",
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: "AIzaSyDAheGqF8-qH5LNLpW2jk83hsqX_D4-0cI",
//     authDomain: "Queen's Place-c73f2.firebaseapp.com",
//     projectId: "Queen's Place-c73f2",
//     storageBucket: "Queen's Place-c73f2.appspot.com",
//     messagingSenderId: "920769746084",
//     appId: "1:920769746084:web:31738e1bc9eacb70f04231",
//     measurementId: "G-Y6HC417FL4",
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
//     appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
//     messagingSenderId: '910516599381',
//     projectId: 'udemy-ac28e',
//     storageBucket: 'udemy-ac28e.appspot.com',
//     iosClientId:
//         '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
//     iosBundleId: 'com.example.fcmtest',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
//     appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
//     messagingSenderId: '910516599381',
//     projectId: 'udemy-ac28e',
//     storageBucket: 'udemy-ac28e.appspot.com',
//     iosClientId:
//         '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
//     iosBundleId: 'com.example.fcmtest',
//   );
// }
